Repository akshitagupta15june/Moksh, pull requests merged in 2023-07, with the labels that each got.

#966 Issue No #908 [FIXED] Spelling mistake in README.md file.
  README.md
Labels: gssoc23, level1

#968 Pomodoro page revamp
  Pomodro_page/reward.css
  Pomodro_page/reward.html
Labels: gssoc23, level2

#988 karma logo to animated logo
  Blogs/Blog.html
  Blogs/karma.html
Labels: gssoc23, level2

#1004 added box shadow to index cards {video attached}
  commonStyles.css
Labels: gssoc23, level1

#1028 [Docs] Fix code blocks alignment in README.md
  README.md
Labels: gssoc23, level1

#1020 fix: alignment of mental health problems
  index.html
Labels: gssoc23, level1

#1030 Back Button added in all blogs
  Blogs/Strength.html
  Blogs/Words.html
  Blogs/cardinalVices.html
  Blogs/depression.html
  Blogs/karma.html
  Blogs/life.html
  Blogs/newBlogStyle.css
Labels: gssoc23, level3

#1033 Navbar Height Reduced
  index.html
Labels: gssoc23, level1

#1032 Fixed blinking issue and Frontend redesign
  shlok_page/motivation.css
  shlok_page/motivation.html
  shlok_page/motivation.js
Labels: gssoc23, level2

#1035 {GSSoC'23} Bug fix of image formats issue#1034
  AR_Meditate/meditation.html
  Blogs/Blog.html
  Blogs/Strength.html
  Blogs/Words.html
  Blogs/cardinalVices.html
  Blogs/depression.html
  Blogs/karma.html
  Blogs/life.html
  Divine_page/story.html
  Images/HeroSection.webp
  Images/New_Logo_2.webp
  Images/OMSymbol.webp
  Images/armed.webp
  Images/logoBgRemoved.webp
  Pomodro_page/reward.html
  commonScript.js
  index.html
  shlok_page/motivation.html
Labels: gssoc23, level2

#1042 Update Words.html to include "Translate Option". Issue Number - 1012
  Blogs/Words.html
Labels: gssoc23, level2

#1048 FixesIssue#1013
  Blogs/Words.html
Labels: gssoc23, level2

#1047 Added translation in despression and suicide blog
  Blogs/depression.html
Labels: gssoc23, level2

#1038 Issue-No-#1001 Resolved - [STYLE CHANGE] Fix the footer on the shlok page .
  shlok_page/motivation.css
  shlok_page/motivation.html
Labels: gssoc23, level2

#1056 Added the google translation box
  Blogs/life.html
Labels: gssoc23, level2

#1068 Styling header
  Rejuvenate_page/rejuvenate.css
  Rejuvenate_page/rejuvenate.html
  Rejuvenate_page/rejuvenate.js
  style.css
Labels: gssoc23, level2

#1082 Recreating shlok page with responsiveness
  shlok_page/motivation.css
  shlok_page/motivation.html
  style.css
Labels: gssoc23, level2

#1084 Fix Shlok Generator Issue
  shlok_page/motivation.css
  shlok_page/motivation.html
  style.css
Labels: gssoc23, level1

#1088 Shlok page work
  shlok_page/motivation.css
  shlok_page/motivation.html
Labels: gssoc23, level1

#1089 Added footer to power of shloks page
  Importance of Sloks/Great People.html
Labels: gssoc23, level1

#1085 Issue #1064 - Update reward.html to modify navbar and footer
  Pomodro_page/reward.html
  commonScript.js
Labels: gssoc23, level2

#1083 Issue No. #794 [BUG FIXED] In the footer section of the site, the copyright year should be dynamically generated instead of being statically hardcoded.
  AR_Meditate/meditation.html
  Divine_page/story.html
  Importance of Sloks/index.html
  Pomodro_page/reward.html
  Rejuvenate_page/rejuvenate.js
  commonScript.js
  copyrightYear.js
  index.html
  shlok_page/motivation.html
Labels: gssoc23

#1094 Fixes issue #1063
  Divine_page/story.css
  Divine_page/story.html
Labels: gssoc23, level2

#1100 Fix issue #1091
  Pomodro_page/reward.css
  Pomodro_page/reward.html
Labels: gssoc23, level2

#1097 fix: 'New Quote' button works on single click
  shlok_page/motivation.js
Labels: gssoc23, level2

#1104 Added the Gita Storyline BackGround
  Gita-Storyline/image4.jpg
  Gita-Storyline/storyline.css
  Gita-Storyline/storyline.html
Labels: gssoc23, level3

#1109 Added a scrollbar in shlok page
  shlok_page/motivation.css
  shlok_page/motivation.html
Labels: gssoc23, level2

#1112 nav bar link fixed
  AR_Meditate/meditation.html
  Rejuvenate_page/rejuvenate.js
  commonScript.js
Labels: gssoc23, level2

#1119 google translate added
  Blogs/cardinalVices.html
Labels: gssoc23, level2

#1126 Issue #1092 Fixed. Updated files to modify navbar
  shlok_page/motivation.css
  shlok_page/motivation.html
  shlok_page/motivation.js
  shlok_page/navbar.js
Labels: gssoc23, level2

#1127 jnavbarcommit
  commonStyles.css
Labels: gssoc23, level1

#1130 Added Gita StoryLine to features
  index.html
Labels: gssoc23, level1

#1090 Feat: Improve the 'power of shlokas' page
  Importance of Sloks/Great People.html
  Importance of Sloks/style.css
Labels: gssoc23, level2

#1143 Added Navbar to Gita Storyline
  Gita-Storyline/storyline.css
  Gita-Storyline/storyline.html
Labels: gssoc23, level2

#1144 fix: positioning of text
  Iskcon/event.html
Labels: gssoc23, level1

#1173 feat: added Bhagwat Geeta section in rejuvenate page
  Rejuvenate_page/rejuvenate.html
Labels: gssoc23, level2

#1172 fixed navbar of divine page
  .vscode/settings.json
  Divine_page/story.html
Labels: gssoc23

#1171 translate alignment fixed
  Blogs/depression.html
Labels: gssoc23, level1

#1169 Navbar in the iskcon page is repaired
  Iskcon/event.html
Labels: gssoc23, level1

#1170 background updated
  shlok_page/motivation.html
Labels: gssoc23, level1

#1175 Added background in Pomodoro page
  Pomodro_page/reward.html
Labels: gssoc23, level1

#1178 update footer of rejuvenate page Fixed #1162
  Rejuvenate_page/rejuvenate.css
  Rejuvenate_page/rejuvenate.html
  Rejuvenate_page/rejuvenate.js
Labels: gssoc23, level1

#1180 Issue No. #1161 [ BUG FIXED ] Navbar in the rejuvenate page is transparent and overlaps with contents on scrolling.
  Rejuvenate_page/rejuvenate.css
Labels: gssoc23, level1

#1183 Issue #1157 Done. Modified navbar
  AR_Meditate/meditation.css
  AR_Meditate/meditation.html
Labels: gssoc23, level2

#1203 Fixes issue #1198
  Pomodro_page/reward.css
  Pomodro_page/reward.html
Labels: gssoc23, level1

#1202 carousel arrow fixed
  Divine_page/story.css
  Divine_page/story.html
Labels: gssoc23, level2

#1200 Changes background color#1197
  quiz_page/quiz.css
  quiz_page/quiz.html
Labels: gssoc23, level2

#1207 changed the styling of timer on pomodoro break page
  Pomodro_page/reward.css
  Pomodro_page/reward.html
  Pomodro_page/reward.js
Labels: gssoc23, level3

#1215 Fix issue #1194 and also added a new footer to AR meditation page(feature added)
  AR_Meditate/meditation.css
  AR_Meditate/meditation.html
  Pomodro_page/reward.html
Labels: gssoc23, level3

#1216 Code refractor
  AR_Meditate/meditation.html
  Divine_page/story.css
  Divine_page/story.html
  Importance of Sloks/Great People.html
  Iskcon/event.html
  Pomodro_page/reward.html
  Rejuvenate_page/rejuvenate.html
  quiz_page/quiz.html
  shlok_page/motivation.css
  shlok_page/motivation.html
Labels: gssoc23, level2

#1224 Issue #1218 Resolved. Completely restructured the html and css files
  Pomodro_page/reward.css
  Pomodro_page/reward.html
  Pomodro_page/reward.js
  Pomodro_page/scroll.js
Labels: gssoc23, level3

#1227 add some properties to fix the button
  Blogs/life.html
Labels: gssoc23, level1

#1236 Added a scroll to top button to the homepage
  commonStyles.css
  image.svg
  index.html
  scrollUp.js
Labels: gssoc23, level2

#1241 [BUG] the color of the navbar is turned to white
  AR_Meditate/meditation.css
Labels: gssoc23, level1

#1250 Issue #1230 Fixed.
  Iskcon/event.css
  Iskcon/event.html
Labels: gssoc23, level2

#1247 fix: download the pdf version of the content of the blogs.
  Blogs/Blog.html
  Blogs/Strength.html
  Blogs/Words.html
  Blogs/cardinalVices.html
  Blogs/depression.html
  Blogs/download.js
  Blogs/karma.html
  Blogs/life.html
Labels: gssoc23, level3

#1248 cards dynamic carousel
  Rejuvenate_page/carouselData.json
  Rejuvenate_page/rejuvenate.html
Labels: gssoc23, level3
