Repository akshitagupta15june/Moksh, pull requests merged in 2023-04, with the labels that each got.

#25 Added google translet feature
  index.html
  script.js
  style.css
Labels: Tarun

#39 Added 2 feature cards to index.html
  Images/read-a-shlok.png
  Images/rejuvenate.png
  index.html
Labels: Devlarabar

#45 Updated event page UI
  event.html
Labels: swapnil

#41 Add Embed video
  README.md
Labels: RUWBAK
