Repository akshitagupta15june/Moksh, pull requests merged in 2024-06, with the labels that each got.

#1629 [BUG] Mobile Interface Issue: Overlapping 'New Quote' Button in Shlokas Tab #1524
  shlok_page/motivation.css
Labels: level1, gssoc

#1620 fixed navbar, menu button and whitish effect issue
  AR_Meditate/meditation.css
  AR_Meditate/meditation.html
  Divine_page/story.html
  index.html
Labels: level2, gssoc

#1614 fixed copy link issue
  .DS_Store
  Blogs/.DS_Store
  Blogs/Blog.html
Labels: level1, gssoc

#1612 Menu is responsive in different dimension
  index.html
  script.js
Labels: level1, gssoc

#1599 fix: initial tweet click contains quote and author
  shlok_page/motivation.js
Labels: level1, gssoc

#1594 Fix/dropdown of search bar in upcoming event section
  Iskcon/event.css
  Iskcon/event.html
  Iskcon/event.js
Labels: level1, gssoc

#1649 Fix Twitter Widget Display Issue in README
  README.md
Labels: level1, gssoc

#1595 Fixed Navbar, color themes of the Power of Knowledge Blogs and Google Translate issues
  Blogs/Blog.html
  Blogs/Strength.html
  Blogs/Words.html
  Blogs/cardinalVices.html
  Blogs/depression.html
  Blogs/fear.html
  Blogs/karma.html
  Blogs/life.html
  Blogs/newBlogStyle.css
  Blogs/translation.js
Labels: level3, gssoc

#1564 Page now responsive after click on read a shlok #1535
  shlok_page/motivation.css
  shlok_page/motivation.html
Labels: level1, gssoc

#1672 fixed navbar menu functionality for small screen devices
  AR_Meditate/meditation.html
Labels: ssoc, beginner

#1674 Alignment of Article section Blue lines and Read box
  index.html
Labels: level1, gssoc

#1686 fixed footer link text in armeditate page
  commonScript.js
  commonStyles.css
Labels: ssoc, beginner

#1692 Improved Meditation Footer Page UI (#1669)
  AR_Meditate/meditation.html
Labels: ssoc, beginner

#1709 Fixed the issue of unwanted space in shlok page
  shlok_page/motivation.css
Labels: level1, gssoc

#1721 issue #1667 solved
  Gita-Storyline/storyline.css
  Gita-Storyline/storyline.html
Labels: ssoc, intermediate

#1711 Fixed the issue of logo
  Divine_page/story.html
Labels: level3, gssoc
